#!/bin/bash

# get the absolute path to this script (SCRIPT_PATH)
# see https://stackoverflow.com/a/12197518
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
while ([ -h "${SCRIPT_PATH}" ]); do
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd > /dev/null

# change directory to libfirm submodule
pushd "${SCRIPT_PATH}/libfirm" > /dev/null

# by default firm is built using debug variant. Other variants
# can be passed as parameter to this script (e.g. optimize)
FIRM_VARIANT="${1:-debug}"

# build libfirm using the provided makefile
make variant="$FIRM_VARIANT"

popd > /dev/null

# copy library, so the run script can find it
mkdir -p lib
cp "${SCRIPT_PATH}/libfirm/build/${FIRM_VARIANT}/libfirm.so" "${SCRIPT_PATH}/lib"


# change the working directory to the project
# (mvn -f <path> is not as flexible)
pushd "$SCRIPT_PATH" > /dev/null

# build the executable with Maven
mvn package "$@"
return_code=$?

# change the working directory back to where we came from
popd > /dev/null
exit $return_code
