#!/bin/bash

# get the absolute path to this script (SCRIPT_PATH)
# see https://stackoverflow.com/a/12197518
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
while ([ -h "${SCRIPT_PATH}" ]); do
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd > /dev/null

# find the compiler executable (EXE_PATH)
EXE_PATH=$(find $SCRIPT_PATH/target/java-compiler-*-with-dependencies.jar) || exit $?

# execute the compiler with the provided arguments and return the exit code
java -jar "$EXE_PATH" "$@"
exit $?