# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Compiler CI with Maven and MJTest

on:
  push:
    branches: 
      # push events on master
      - master
      # push events on releases branch
      - 'releases/**'
    branches-ignore:
     - 'noci/**'
  pull_request:
    branches: 
      # push events on master
      - master
      # push events on releases branch
      - 'releases/**' 
    branches-ignore:
     - 'noci/**'
  schedule:
   - cron : '0 0 * * *'
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - [published, created, edited]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Install MJTests and Tests Package 
      run: git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest.git
    - name: Copy Artifacts
      run: mkdir staging && cp target/*.jar staging
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

  
